"use client";

import { cloneElement, useMemo, useState, type ReactElement } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  CheckCircle2,
  BookOpen,
  ChevronLeft,
  ChevronRight,
  Clock3,
  Download,
  FileText,
  Loader2,
  Sparkles,
} from "lucide-react";
import { MarkdownRenderer } from "./markdown-renderer";
import type { PaperSection } from "@/lib/types";

interface ReaderPage {
  title: string;
  content: string;
}

function markdownToLatex(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];

  for (const line of lines) {
    const h3 = line.match(/^###\s+(.+)$/);
    if (h3) { out.push(`\\subsection{${h3[1]}}`); continue; }

    const h2 = line.match(/^##\s+(.+)$/);
    if (h2) { out.push(`\\section{${h2[1]}}`); continue; }

    const h1 = line.match(/^#\s+(.+)$/);
    if (h1) { out.push(`\\chapter{${h1[1]}}`); continue; }

    out.push(line);
  }

  return out
    .join("\n")
    .replace(/\$\$([\s\S]*?)\$\$/g, "\\[$1\\]")
    .replace(/\$(.*?)\$/g, "\\($1\\)")
    .replace(/\*\*\*(.*?)\*\*\*/g, "\\textbf{\\textit{$1}}")
    .replace(/\*\*(.*?)\*\*/g, "\\textbf{$1}")
    .replace(/\*(.*?)\*/g, "\\textit{$1}");
}

function exportLatex(sections: PaperSection[]) {
  const content = markdownToLatex(sections.map((s) => s.content).join("\n\n"));

  const latex = `\\documentclass[12pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath,amssymb}
\\usepackage{amsthm}
\\usepackage{hyperref}
\\usepackage{geometry}
\\geometry{margin=1in}

\\title{PaperForge --- Model Setup}
\\author{Generated by PaperForge}
\\date{\\today}

\\begin{document}
\\maketitle

${content}

\\end{document}
`;

  const blob = new Blob([latex], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "paperforge-model-setup.tex";
  a.click();
  URL.revokeObjectURL(url);
}

function cleanHeading(title: string) {
  return title.replace(/^#+\s*/, "").replace(/\*\*/g, "").trim();
}

function splitMarkdownPages(content: string, fallbackTitle: string): ReaderPage[] {
  const normalized = content.trim();
  if (!normalized) return [];

  const headingRegex = /^#{2,3}\s+.+$/gm;
  const matches = Array.from(normalized.matchAll(headingRegex)).filter(
    (match) => !/^##\s+Model Setup/i.test(match[0].trim())
  );

  if (matches.length === 0) {
    return [{ title: fallbackTitle, content: normalized }];
  }

  const intro = normalized.slice(0, matches[0].index).trim();
  const pages: ReaderPage[] = intro
    ? [
        {
          title: "Overview",
          content: intro.replace(/^##\s+Model Setup\s*/i, "").trim(),
        },
      ]
    : [];

  matches.forEach((match, index) => {
    const start = match.index ?? 0;
    const end =
      index + 1 < matches.length
        ? matches[index + 1].index ?? normalized.length
        : normalized.length;
    const chunk = normalized.slice(start, end).trim();

    pages.push({
      title: cleanHeading(match[0]),
      content: chunk,
    });
  });

  return pages.filter((page) => page.content.length > 0);
}

function clampPage(page: number, count: number) {
  if (count <= 0) return 0;
  return Math.min(Math.max(page, 0), count - 1);
}

interface OutputPanelProps {
  sections: PaperSection[];
  isGenerating: boolean;
  onGenerate: () => void;
  literatureContent?: string;
  isLoadingLiterature?: boolean;
  onGenerateReferences?: () => void;
}

export function OutputPanel({
  sections,
  isGenerating,
  onGenerate,
  literatureContent = "",
  isLoadingLiterature = false,
  onGenerateReferences,
}: OutputPanelProps) {
  const [activeView, setActiveView] = useState<"model" | "references">("model");
  const [modelPage, setModelPage] = useState(0);
  const [referencePage, setReferencePage] = useState(0);

  const modelSections = sections.filter(
    (section) => !/reference|literature|文献/i.test(section.title)
  );
  const referenceSections = sections.filter((section) =>
    /reference|literature|文献/i.test(section.title)
  );
  const generatedContent = modelSections
    .map((section) => section.content)
    .join("\n\n");
  const persistedReferences = referenceSections
    .map((section) => section.content)
    .join("\n\n");
  const referenceContent = literatureContent || persistedReferences;
  const modelPages = useMemo(
    () => splitMarkdownPages(generatedContent, "Model Setup"),
    [generatedContent]
  );
  const referencePages = useMemo(
    () => splitMarkdownPages(referenceContent, "References"),
    [referenceContent]
  );

  const safeModelPage = clampPage(modelPage, modelPages.length);
  const safeReferencePage = clampPage(referencePage, referencePages.length);
  const hasGenerated = modelSections.length > 0;

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex flex-col gap-3 rounded-lg border bg-card/70 px-4 py-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary/10">
            <FileText className="h-4 w-4 text-primary" />
          </div>
          <div>
            <h2 className="text-sm font-semibold">生成内容</h2>
            <p className="text-xs text-muted-foreground">
              Model Setup、参考文献和导出操作集中在这里
            </p>
          </div>
          {hasGenerated && (
            <Badge variant="secondary" className="text-[10px]">
              {modelPages.length} 页正文
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-2">
          {hasGenerated && (
            <Button
              variant="outline"
              size="sm"
              className="h-8 gap-1.5"
              onClick={() => exportLatex(modelSections)}
            >
              <Download className="h-3.5 w-3.5" />
              导出 LaTeX
            </Button>
          )}
          <Button
            onClick={onGenerate}
            disabled={isGenerating || hasGenerated}
            size="sm"
            className="h-8 gap-1.5"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                生成中...
              </>
            ) : hasGenerated ? (
              "已生成"
            ) : (
              <>
                <Sparkles className="h-3.5 w-3.5" />
                生成 Model Setup
              </>
            )}
          </Button>
        </div>
      </div>

      {!hasGenerated && (
        <Card className="min-h-[520px] overflow-hidden border-0 ring-1 ring-border">
          <div className="h-0.5 bg-primary" />
          <CardContent className="p-6">
            {!isGenerating && (
              <div className="flex min-h-[460px] flex-col items-center justify-center text-center">
                <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-muted">
                  <FileText className="h-6 w-6 text-muted-foreground" />
                </div>
                <h3 className="text-base font-semibold">等待生成正文</h3>
                <p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">
                  完成左侧模型定义后，点击上方按钮生成 Model Setup。生成后这里会切换成分页阅读视图。
                </p>
                <div className="mt-5 grid w-full max-w-md gap-2 text-left sm:grid-cols-3">
                  <OutputHint icon={<CheckCircle2 />} text="模型定义" />
                  <OutputHint icon={<Sparkles />} text="生成章节" />
                  <OutputHint icon={<Download />} text="导出 LaTeX" />
                </div>
              </div>
            )}
            {isGenerating && (
              <div className="flex min-h-[460px] flex-col justify-center">
                <div className="mx-auto flex max-w-md items-start gap-3 rounded-lg border bg-background/70 p-4">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-primary/10">
                    <Loader2 className="h-5 w-5 animate-spin text-primary" />
                  </div>
                  <div className="space-y-1">
                    <p className="text-sm font-semibold">AI 正在生成内容</p>
                    <p className="text-sm leading-6 text-muted-foreground">
                      正在组织论文正文和数学表述，页面会保持在当前工作区。
                    </p>
                    <div className="flex items-center gap-1.5 pt-1 text-xs text-muted-foreground">
                      <Clock3 className="h-3.5 w-3.5" />
                      通常需要 30 秒左右
                    </div>
                  </div>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {hasGenerated && (
        <div className="space-y-4">
          <div className="flex flex-wrap items-center gap-2">
            <Button
              variant={activeView === "model" ? "default" : "outline"}
              size="sm"
              className="gap-1.5"
              onClick={() => setActiveView("model")}
            >
              <FileText className="h-3.5 w-3.5" />
              Model Setup
            </Button>
            <Button
              variant={activeView === "references" ? "default" : "outline"}
              size="sm"
              className="gap-1.5"
              onClick={() => {
                setActiveView("references");
                if (!referenceContent && !isLoadingLiterature) {
                  onGenerateReferences?.();
                }
              }}
            >
              <BookOpen className="h-3.5 w-3.5" />
              参考文献
              {isLoadingLiterature && <Loader2 className="h-3 w-3 animate-spin" />}
            </Button>
          </div>

          {activeView === "model" && modelPages[safeModelPage] && (
            <ReaderCard
              page={modelPages[safeModelPage]}
              pageIndex={safeModelPage}
              pageCount={modelPages.length}
              onPrevious={() =>
                setModelPage((page) => clampPage(page - 1, modelPages.length))
              }
              onNext={() =>
                setModelPage((page) => clampPage(page + 1, modelPages.length))
              }
            />
          )}

          {activeView === "references" && (
            <Card className="min-h-[520px] overflow-hidden border-0 ring-1 ring-border">
              <div className="h-0.5 bg-primary" />
              <CardContent className="p-6">
                {isLoadingLiterature && !referencePages[safeReferencePage] ? (
                  <div className="flex min-h-[420px] items-center justify-center">
                    <div className="flex items-center gap-3 rounded-lg border bg-background/70 p-4">
                      <Loader2 className="h-5 w-5 animate-spin text-primary" />
                      <div>
                        <p className="text-sm font-medium">正在生成参考文献推荐</p>
                        <p className="mt-1 text-xs text-muted-foreground">
                          会根据当前模型匹配经典文献方向
                        </p>
                      </div>
                    </div>
                  </div>
                ) : referencePages[safeReferencePage] ? (
                  <ReaderBody
                    page={referencePages[safeReferencePage]}
                    pageIndex={safeReferencePage}
                    pageCount={referencePages.length}
                    onPrevious={() =>
                      setReferencePage((page) =>
                        clampPage(page - 1, referencePages.length)
                      )
                    }
                    onNext={() =>
                      setReferencePage((page) =>
                        clampPage(page + 1, referencePages.length)
                      )
                    }
                  />
                ) : (
                  <div className="flex min-h-[420px] flex-col items-center justify-center text-center">
                    <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-muted">
                      <BookOpen className="h-6 w-6 text-muted-foreground" />
                    </div>
                    <h3 className="text-base font-semibold">参考文献还没有生成</h3>
                    <p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">
                      点击“参考文献”后会自动请求推荐；如果没有开始，请重新切换此标签。
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>
      )}
    </div>
  );
}

function ReaderCard({
  page,
  pageIndex,
  pageCount,
  onPrevious,
  onNext,
}: {
  page: ReaderPage;
  pageIndex: number;
  pageCount: number;
  onPrevious: () => void;
  onNext: () => void;
}) {
  return (
    <Card className="ring-1 ring-border overflow-hidden">
      <div className="h-0.5 bg-primary" />
      <CardContent className="p-6">
        <ReaderBody
          page={page}
          pageIndex={pageIndex}
          pageCount={pageCount}
          onPrevious={onPrevious}
          onNext={onNext}
        />
      </CardContent>
    </Card>
  );
}

function OutputHint({
  icon,
  text,
}: {
  icon: ReactElement<{ className?: string }>;
  text: string;
}) {
  return (
    <div className="flex items-center gap-2 rounded-md border bg-background/70 px-3 py-2 text-xs text-muted-foreground">
      {cloneElement(icon, {
        className: "h-3.5 w-3.5 text-primary",
      })}
      <span>{text}</span>
    </div>
  );
}

function ReaderBody({
  page,
  pageIndex,
  pageCount,
  onPrevious,
  onNext,
}: {
  page: ReaderPage;
  pageIndex: number;
  pageCount: number;
  onPrevious: () => void;
  onNext: () => void;
}) {
  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <p className="text-xs text-muted-foreground">
            第 {pageIndex + 1} / {pageCount} 页
          </p>
          <h3 className="truncate text-lg font-semibold">{page.title}</h3>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={onPrevious}
            disabled={pageIndex === 0}
          >
            <ChevronLeft className="h-3.5 w-3.5" />
            上一页
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={onNext}
            disabled={pageIndex >= pageCount - 1}
          >
            下一页
            <ChevronRight className="h-3.5 w-3.5" />
          </Button>
        </div>
      </div>
      <div className="reader-page min-h-[420px]">
        <MarkdownRenderer content={page.content} />
      </div>
    </div>
  );
}
